// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getImg/getImg.proto

package getImg

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetImg service

func NewGetImgEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetImg service

type GetImgService interface {
	MicroGetImg(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getImgService struct {
	c    client.Client
	name string
}

func NewGetImgService(name string, c client.Client) GetImgService {
	return &getImgService{
		c:    c,
		name: name,
	}
}

func (c *getImgService) MicroGetImg(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetImg.MicroGetImg", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetImg service

type GetImgHandler interface {
	MicroGetImg(context.Context, *Request, *Response) error
}

func RegisterGetImgHandler(s server.Server, hdlr GetImgHandler, opts ...server.HandlerOption) error {
	type getImg interface {
		MicroGetImg(ctx context.Context, in *Request, out *Response) error
	}
	type GetImg struct {
		getImg
	}
	h := &getImgHandler{hdlr}
	return s.Handle(s.NewHandler(&GetImg{h}, opts...))
}

type getImgHandler struct {
	GetImgHandler
}

func (h *getImgHandler) MicroGetImg(ctx context.Context, in *Request, out *Response) error {
	return h.GetImgHandler.MicroGetImg(ctx, in, out)
}
